CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task TEXT NOT NULL,
  type TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
  end_at TEXT NOT NULL,
  class_id INTEGER NOT NULL,
  lesson_id INTEGER NOT NULL,
  student_id INTEGER DEFAULT NULL,
  FOREIGN KEY (class_id) REFERENCES classes (id) ON DELETE CASCADE,
  FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
  FOREIGN KEY (student_id) REFERENCES student_details (id) ON DELETE CASCADE
)