CREATE TABLE IF NOT EXISTS classes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  school_id INTEGER NOT NULL UNIQUE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);