name: Build and Push Nginx

on:
  push:
    branches:
      - main
    paths:
      - "nginx/**"
      - "Dockerfile.nginx"
      - ".github/workflows/nginx.yml"

jobs:
  build-nginx:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: crascot/onschool-nginx

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.nginx
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
