name: Build and Push Server

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "package.json"
      - "package-lock.json"
      - "tsconfig*.json"
      - "nest-cli.json"
      - "Dockerfile"
      - ".dockerignore"
      - ".github/workflows/server.yml"

jobs:
  build-server:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: crascot/onschool-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: ./onschool_server
          file: ./onschool_server/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
